"""
Pydantic Schemas for Query API and Health Check
"""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field, field_validator


class QueryRequest(BaseModel):
    """Incoming query payload from client."""
    question: str = Field(
        ...,
        description="The question or prompt to ask about the indexed documents.",
        examples=["What is the difference between TCP and UDP?"]
    )

    @field_validator("question")
    @classmethod
    def validate_question(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Question cannot be empty or contain only whitespace.")
        if len(stripped) < 3:
            raise ValueError("Question must be at least 3 characters long.")
        return stripped


class SourceItem(BaseModel):
    """Citation metadata for a retrieved document chunk."""
    document: str = Field(
        ...,
        description="The filename or title of the referenced document.",
        examples=["cs104_computer_networks.pdf"]
    )
    page: int = Field(
        ...,
        description="The 1-indexed page number in the source document.",
        examples=[3]
    )
    relevance_score: Optional[float] = Field(
        default=None,
        description="Similarity or relevance score computed by the vector store."
    )
    snippet: Optional[str] = Field(
        default=None,
        description="A preview snippet of the retrieved text used to answer the question."
    )


class QueryResponse(BaseModel):
    """Grounded answer response with source citations."""
    answer: str = Field(
        ...,
        description="The grounded answer generated by the LLM from retrieved context."
    )
    sources: List[SourceItem] = Field(
        default_factory=list,
        description="List of cited source documents and pages supporting the answer."
    )


class HealthResponse(BaseModel):
    """System health and component status response."""
    status: str = Field(
        default="healthy",
        description="Overall service health status ('healthy', 'degraded', 'unhealthy')."
    )
    components: Dict[str, Any] = Field(
        default_factory=dict,
        description="Individual status of vector store, embedding model, and Ollama connection."
    )
    details: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Additional diagnostic details (e.g. collection count, model name)."
    )
